name: CI/CD Pipeline - Build & Push Docker

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      - name: Build with Maven
        run: |
          cd studentAPI/studentAPI
          mvn -B clean package -DskipTests

      - name: Build Docker image
        run: |
          cd studentAPI/studentAPI
          docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/student-management:latest \
                       -t ${{ secrets.DOCKERHUB_USERNAME }}/student-management:${{ github.sha }} .

      - name: Log in to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image
        run: |
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/student-management:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/student-management:${{ github.sha }}
